### ISSUE TITLE
Recurring events not in sync with google calendar

### ISSUE THREAD

**Issue by onmondo** [crashspringfield/react-google-calendar#2]
![image](https://user-images.githubusercontent.com/6768671/48054828-1c1b9780-e1e9-11e8-966b-0bc8ad0380c3.png)

![image](https://user-images.githubusercontent.com/6768671/48054931-5ab15200-e1e9-11e8-9ca6-9d054dbcaced.png)

As you'll notice, both calendars (first one from google and the second one from this repo run locally) are not in sync. It seems there is a problem with the mapping of recurring events.

**Comment by matthewboman** [comment]
Thanks for sharing this. Would you mind sharing the steps to reproduce? What are the recurrence settings on your Google calendar?

**Comment by onmondo** [comment]
Hi @crashspringfield , the event scheduled on my calendar has no specific time so I think your algorithm for recurring events needs to handle dates without time constraints. I've already done the fix on my local machine.

**Comment by matthewboman** [comment]
@onmondo I updated the various recurring events to account for all day events and everything seemed ok in the integration tests. I'm going to go back and write unit tests, but let me know if this still poses and issue.
