### ISSUE TITLE
webpack-dev-server Missing Origin Validation

### ISSUE THREAD

**Issue by bradleyy1012** [crashspringfield/react-google-calendar#6]
I ran npm audit and found 1 high security vulnerability. 
<img width="726" alt="screen shot 2018-11-11 at 8 21 47 pm" src="https://user-images.githubusercontent.com/4410719/48324745-781e5b80-e5ef-11e8-84fe-f3612a47de4b.png">

**Comment by matthewboman** [comment]
Thanks! It looks like this should only affect your dev environment, but I'll get on updating depenencies to fix this.
